version: '3.8'

services:
  app:
    container_name: weather-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/weather.db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.sqlite.JDBC
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.community.dialect.SQLiteDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_URL=${WEATHER_API_URL}
      - WEATHERSTACK_URL=${WEATHERSTACK_URL}
      - WEATHERSTACK_KEY=${WEATHERSTACK_KEY}
    volumes:
      - ./data:/data
    restart: unless-stopped